export interface Perfume {
  id: string;
  slug: string;
  name: string;
  brand: string;
  year: number;
  gender: 'men' | 'women' | 'unisex';
  concentration: 'Parfum' | 'EDP' | 'EDT' | 'EDC' | 'Cologne';
  price: number;
  image: string;
  accords: { name: string; intensity: number }[];
  notes: { top: string[]; heart: string[]; base: string[] };
  ratings: { longevity: number; sillage: number; overall: number };
  seasons: ('Spring' | 'Summer' | 'Fall' | 'Winter')[];
  occasions: string[];
  description: string;
  dupeOf?: string;
  tags: string[];
}

const IMAGES = [
  'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
  'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&q=80',
  'https://images.unsplash.com/photo-1595425970377-c9703cf48b6b?w=400&q=80',
  'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80',
  'https://images.unsplash.com/photo-1588776814546-1ffbb6d0ef44?w=400&q=80',
  'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=400&q=80',
  'https://images.unsplash.com/photo-1582402891898-4e73e8b97d2c?w=400&q=80',
  'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400&q=80',
  'https://images.unsplash.com/photo-1616739919219-bf4832db0afe?w=400&q=80',
  'https://images.unsplash.com/photo-1621634002586-6d26b2fc2b55?w=400&q=80',
  'https://images.unsplash.com/photo-1590156206657-aec9fc82fce0?w=400&q=80',
  'https://images.unsplash.com/photo-1562887100-4c6ac6e30dd5?w=400&q=80',
  'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=400&q=80',
  'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400&q=80',
  'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&q=80',
  'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&q=80',
  'https://images.unsplash.com/photo-1506755594592-349d12a7c52a?w=400&q=80',
  'https://images.unsplash.com/photo-1563170351-be9e0ff0cd5f?w=400&q=80',
  'https://images.unsplash.com/photo-1609087055804-7c41f8cd5da5?w=400&q=80',
  'https://images.unsplash.com/photo-1575995872537-3793d29d972c?w=400&q=80',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80',
  'https://images.unsplash.com/photo-1617897903246-719242758050?w=400&q=80',
  'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400&q=80',
  'https://images.unsplash.com/photo-1623609163859-ca93c959b5b8?w=400&q=80',
  'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
  'https://images.unsplash.com/photo-1525904097878-94fb15835963?w=400&q=80',
  'https://images.unsplash.com/photo-1600612253971-81b8d1e4a891?w=400&q=80',
  'https://images.unsplash.com/photo-1551034549-9c59ae843a87?w=400&q=80',
  'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80',
  'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&q=80',
  'https://images.unsplash.com/photo-1571994500685-2b32e81b6b14?w=400&q=80',
  'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80',
  'https://images.unsplash.com/photo-1584837861171-3ccf1b3f4e9d?w=400&q=80',
  'https://images.unsplash.com/photo-1617940673100-56f6b3daa0e4?w=400&q=80',
  'https://images.unsplash.com/photo-1583484963886-cfe2bff2945f?w=400&q=80',
  'https://images.unsplash.com/photo-1611509538834-dd71dc5c92bb?w=400&q=80',
  'https://images.unsplash.com/photo-1603217040830-aa6cc1e8aae0?w=400&q=80',
  'https://images.unsplash.com/photo-1638532163975-4bf5d04c92f9?w=400&q=80',
  'https://images.unsplash.com/photo-1614093302611-8aba62f0a9f0?w=400&q=80',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&q=80',
  'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
  'https://images.unsplash.com/photo-1590156206657-aec9fc82fce0?w=400&q=80',
  'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
  'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&q=80',
  'https://images.unsplash.com/photo-1595425970377-c9703cf48b6b?w=400&q=80',
  'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80',
  'https://images.unsplash.com/photo-1588776814546-1ffbb6d0ef44?w=400&q=80',
  'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=400&q=80',
  'https://images.unsplash.com/photo-1582402891898-4e73e8b97d2c?w=400&q=80',
  'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400&q=80',
];

export const PERFUMES: Perfume[] = [
  {
    id: '1',
    slug: 'baccarat-rouge-540',
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    year: 2015,
    gender: 'unisex',
    concentration: 'EDP',
    price: 325,
    image: IMAGES[0],
    accords: [
      { name: 'Woody', intensity: 85 },
      { name: 'Amber', intensity: 78 },
      { name: 'Floral', intensity: 60 },
      { name: 'Sweet', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Saffron', 'Jasmine'],
      heart: ['Amberwood', 'Ambergris', 'Fir Resin'],
      base: ['Oakmoss', 'Cedar'],
    },
    ratings: { longevity: 5, sillage: 5, overall: 9.2 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night', 'special-occasion'],
    description: 'A luminous floral-woody fragrance with crystalline amber and cedar notes. Iconic and beloved.',
    tags: ['iconic', 'best-seller', 'date-night'],
  },
  {
    id: '2',
    slug: 'bleu-de-chanel',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    year: 2010,
    gender: 'men',
    concentration: 'EDP',
    price: 145,
    image: IMAGES[1],
    accords: [
      { name: 'Woody', intensity: 80 },
      { name: 'Citrus', intensity: 70 },
      { name: 'Aromatic', intensity: 65 },
      { name: 'Fresh', intensity: 55 },
      { name: 'Musky', intensity: 40 },
    ],
    notes: {
      top: ['Citrus', 'Mint', 'Pink Pepper'],
      heart: ['Ginger', 'Nutmeg', 'Jasmine'],
      base: ['Labdanum', 'Vetiver', 'Sandalwood', 'Cedar'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.6 },
    seasons: ['Spring', 'Fall'],
    occasions: ['office', 'everyday', 'date-night'],
    description: 'A timeless, virile fragrance that breaks free from convention with fresh citrus and deep woods.',
    tags: ['classic', 'versatile', 'office'],
  },
  {
    id: '3',
    slug: 'sauvage-dior',
    name: 'Sauvage',
    brand: 'Dior',
    year: 2015,
    gender: 'men',
    concentration: 'EDP',
    price: 130,
    image: IMAGES[2],
    accords: [
      { name: 'Aromatic', intensity: 82 },
      { name: 'Woody', intensity: 70 },
      { name: 'Fresh', intensity: 65 },
      { name: 'Spicy', intensity: 50 },
      { name: 'Musky', intensity: 48 },
    ],
    notes: {
      top: ['Bergamot', 'Pepper'],
      heart: ['Sichuan Pepper', 'Lavender', 'Pink Pepper', 'Vetiver', 'Patchouli', 'Geranium', 'Elemi'],
      base: ['Ambroxan', 'Cedar', 'Labdanum'],
    },
    ratings: { longevity: 5, sillage: 5, overall: 8.9 },
    seasons: ['Spring', 'Summer', 'Fall'],
    occasions: ['everyday', 'office', 'outdoor'],
    description: 'A radically fresh composition blending raw and noble materials — from Ambroxan to bergamot.',
    tags: ['fresh', 'masculine', 'everyday'],
  },
  {
    id: '4',
    slug: 'black-orchid-tom-ford',
    name: 'Black Orchid',
    brand: 'Tom Ford',
    year: 2006,
    gender: 'unisex',
    concentration: 'EDP',
    price: 195,
    image: IMAGES[3],
    accords: [
      { name: 'Floral', intensity: 78 },
      { name: 'Woody', intensity: 72 },
      { name: 'Sweet', intensity: 65 },
      { name: 'Dark', intensity: 60 },
      { name: 'Spicy', intensity: 50 },
    ],
    notes: {
      top: ['Black Truffle', 'Ylang-Ylang', 'Bergamot', 'Black Currant'],
      heart: ['Black Orchid', 'Fruit', 'Lotus Wood', 'Jasmine', 'Gardenia', 'Dark Chocolate', 'Spice'],
      base: ['Patchouli', 'Vetiver', 'Sandalwood', 'Amber', 'Incense', 'Oakmoss', 'Vanilla'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.0 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night', 'special-occasion'],
    description: 'A luxurious and sensual blend of dark and languid florals with the rich notes of black truffle.',
    tags: ['dark', 'sensual', 'evening'],
  },
  {
    id: '5',
    slug: 'chance-chanel',
    name: 'Chance Eau Tendre',
    brand: 'Chanel',
    year: 2010,
    gender: 'women',
    concentration: 'EDP',
    price: 155,
    image: IMAGES[4],
    accords: [
      { name: 'Floral', intensity: 85 },
      { name: 'Citrus', intensity: 72 },
      { name: 'Fresh', intensity: 68 },
      { name: 'Powdery', intensity: 45 },
      { name: 'Musky', intensity: 40 },
    ],
    notes: {
      top: ['Grapefruit', 'Quince'],
      heart: ['Hyacinth', 'Jasmine'],
      base: ['White Musk', 'Cedar', 'Ambergris'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 8.1 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'office', 'brunch'],
    description: 'A fresh floral fragrance that embodies the spirit of spontaneity and the joy of the unexpected.',
    tags: ['fresh', 'feminine', 'everyday'],
  },
  {
    id: '6',
    slug: 'oud-wood-tom-ford',
    name: 'Oud Wood',
    brand: 'Tom Ford',
    year: 2007,
    gender: 'unisex',
    concentration: 'EDP',
    price: 225,
    image: IMAGES[5],
    accords: [
      { name: 'Oud', intensity: 88 },
      { name: 'Woody', intensity: 80 },
      { name: 'Spicy', intensity: 55 },
      { name: 'Smoky', intensity: 50 },
      { name: 'Vanilla', intensity: 42 },
    ],
    notes: {
      top: ['Oud', 'Rosewood', 'Cardamom'],
      heart: ['Sandalwood', 'Vetiver', 'Tonka Bean'],
      base: ['Amber', 'Musk'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.1 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night', 'special-occasion'],
    description: 'A groundbreaking oud fragrance that made oud approachable for Western audiences.',
    tags: ['oud', 'luxury', 'evening'],
  },
  {
    id: '7',
    slug: 'flowerbomb-viktor-rolf',
    name: 'Flowerbomb',
    brand: 'Viktor&Rolf',
    year: 2005,
    gender: 'women',
    concentration: 'EDP',
    price: 120,
    image: IMAGES[6],
    accords: [
      { name: 'Floral', intensity: 90 },
      { name: 'Sweet', intensity: 75 },
      { name: 'Powdery', intensity: 60 },
      { name: 'Vanilla', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Bergamot', 'Tea'],
      heart: ['Sambac Jasmine', 'Cattleya Orchid', 'Rose', 'Freesia', 'Peony'],
      base: ['Patchouli', 'Musk', 'Vanilla'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.5 },
    seasons: ['Fall', 'Winter', 'Spring'],
    occasions: ['evening', 'date-night', 'everyday'],
    description: 'An explosion of flowers — a concentrate of femininity and sensuality.',
    tags: ['floral', 'feminine', 'date-night'],
  },
  {
    id: '8',
    slug: 'la-vie-est-belle-lancome',
    name: 'La Vie est Belle',
    brand: 'Lancôme',
    year: 2012,
    gender: 'women',
    concentration: 'EDP',
    price: 98,
    image: IMAGES[7],
    accords: [
      { name: 'Sweet', intensity: 82 },
      { name: 'Floral', intensity: 72 },
      { name: 'Powdery', intensity: 65 },
      { name: 'Vanilla', intensity: 60 },
      { name: 'Fruity', intensity: 45 },
    ],
    notes: {
      top: ['Black Currant', 'Pear'],
      heart: ['Iris', 'Jasmine', 'Orange Blossom'],
      base: ['Praline', 'Vanilla', 'Patchouli', 'Musk', 'Tonka Bean'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.3 },
    seasons: ['Fall', 'Winter'],
    occasions: ['everyday', 'date-night', 'evening'],
    description: 'Life is beautiful — a floriental fragrance built around a rich iris patchouli accord.',
    tags: ['sweet', 'feminine', 'popular'],
  },
  {
    id: '9',
    slug: 'good-girl-carolina-herrera',
    name: 'Good Girl',
    brand: 'Carolina Herrera',
    year: 2016,
    gender: 'women',
    concentration: 'EDP',
    price: 115,
    image: IMAGES[8],
    accords: [
      { name: 'Floral', intensity: 80 },
      { name: 'Sweet', intensity: 70 },
      { name: 'Woody', intensity: 55 },
      { name: 'Powdery', intensity: 50 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Almond', 'Coffee'],
      heart: ['Tuberose', 'Jasmine'],
      base: ['Tonka Bean', 'Cacao', 'Sandalwood', 'Vetiver', 'Myrrh'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.4 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night', 'special-occasion'],
    description: 'A duality between good and bad, day and night — jasmine meets cocoa and coffee.',
    tags: ['feminine', 'dark', 'evening'],
  },
  {
    id: '10',
    slug: 'acqua-di-gio-armani',
    name: 'Acqua di Giò',
    brand: 'Giorgio Armani',
    year: 1996,
    gender: 'men',
    concentration: 'EDT',
    price: 85,
    image: IMAGES[9],
    accords: [
      { name: 'Marine', intensity: 88 },
      { name: 'Fresh', intensity: 82 },
      { name: 'Citrus', intensity: 70 },
      { name: 'Aromatic', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Calabrian Bergamot', 'Neroli', 'Green Tangerine', 'Rosemary'],
      heart: ['Rosewood', 'Persimmon', 'Jasmine', 'Marine Notes'],
      base: ['White Musk', 'Cedar', 'Patchouli'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 8.0 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'outdoor', 'beach'],
    description: 'A Mediterranean ode to the sea — fresh, marine, and effortlessly masculine.',
    tags: ['fresh', 'summer', 'classic'],
  },
  {
    id: '11',
    slug: 'tobacco-vanille-tom-ford',
    name: 'Tobacco Vanille',
    brand: 'Tom Ford',
    year: 2007,
    gender: 'unisex',
    concentration: 'EDP',
    price: 250,
    image: IMAGES[10],
    accords: [
      { name: 'Vanilla', intensity: 90 },
      { name: 'Sweet', intensity: 82 },
      { name: 'Tobacco', intensity: 75 },
      { name: 'Spicy', intensity: 60 },
      { name: 'Warm', intensity: 55 },
    ],
    notes: {
      top: ['Tobacco Leaf', 'Spices'],
      heart: ['Tobacco Blossom', 'Jasmine', 'Vanilla'],
      base: ['Tonka Bean', 'Cacao', 'Dried Fruit', 'Wood Sap'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.0 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: 'Rich tobacco blended with sweet vanilla — a warm, indulgent and spicy oriental.',
    tags: ['tobacco', 'vanilla', 'luxury'],
  },
  {
    id: '12',
    slug: 'miss-dior',
    name: 'Miss Dior',
    brand: 'Dior',
    year: 2017,
    gender: 'women',
    concentration: 'EDP',
    price: 140,
    image: IMAGES[11],
    accords: [
      { name: 'Floral', intensity: 88 },
      { name: 'Powdery', intensity: 65 },
      { name: 'Fresh', intensity: 58 },
      { name: 'Citrus', intensity: 50 },
      { name: 'Musky', intensity: 42 },
    ],
    notes: {
      top: ['Aldehydes', 'Bergamot'],
      heart: ['Grasse Rose', 'Peony', 'Lily of the Valley'],
      base: ['Sandalwood', 'Musk', 'Patchouli'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 8.2 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'brunch', 'date-night'],
    description: 'A bouquet of peonies and roses — fresh, feminine and timeless.',
    tags: ['floral', 'feminine', 'classic'],
  },
  {
    id: '13',
    slug: 'aventus-creed',
    name: 'Aventus',
    brand: 'Creed',
    year: 2010,
    gender: 'men',
    concentration: 'EDP',
    price: 435,
    image: IMAGES[12],
    accords: [
      { name: 'Fruity', intensity: 80 },
      { name: 'Smoky', intensity: 72 },
      { name: 'Woody', intensity: 68 },
      { name: 'Fresh', intensity: 60 },
      { name: 'Musky', intensity: 50 },
    ],
    notes: {
      top: ['Pineapple', 'Bergamot', 'Black Currant', 'Apple'],
      heart: ['Birch', 'Patchouli', 'Rose', 'Jasmine'],
      base: ['Musk', 'Oakmoss', 'Ambergris', 'Vanilla'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 9.1 },
    seasons: ['Spring', 'Fall'],
    occasions: ['date-night', 'office', 'special-occasion'],
    description: 'Inspired by the life of Napoleon Bonaparte — bold, strong, powerful and successful.',
    tags: ['masculine', 'luxury', 'iconic'],
  },
  {
    id: '14',
    slug: 'neroli-portofino-tom-ford',
    name: 'Neroli Portofino',
    brand: 'Tom Ford',
    year: 2011,
    gender: 'unisex',
    concentration: 'EDP',
    price: 225,
    image: IMAGES[13],
    accords: [
      { name: 'Citrus', intensity: 90 },
      { name: 'Fresh', intensity: 82 },
      { name: 'Floral', intensity: 65 },
      { name: 'Marine', intensity: 55 },
      { name: 'Musky', intensity: 42 },
    ],
    notes: {
      top: ['Bergamot', 'Lemon', 'Mandarin Orange', 'Bitter Orange'],
      heart: ['Neroli', 'Jasmine', 'Pitosporo'],
      base: ['Amber', 'Musk', 'Oakmoss'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 8.4 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'outdoor', 'beach'],
    description: 'The sun-drenched Italian Riviera captured in a bottle — sparkling citrus and neroli.',
    tags: ['citrus', 'summer', 'unisex'],
  },
  {
    id: '15',
    slug: 'shalimar-guerlain',
    name: 'Shalimar',
    brand: 'Guerlain',
    year: 1925,
    gender: 'women',
    concentration: 'EDP',
    price: 110,
    image: IMAGES[14],
    accords: [
      { name: 'Oriental', intensity: 88 },
      { name: 'Vanilla', intensity: 80 },
      { name: 'Powdery', intensity: 70 },
      { name: 'Floral', intensity: 55 },
      { name: 'Smoky', intensity: 50 },
    ],
    notes: {
      top: ['Bergamot', 'Lemon', 'Neroli'],
      heart: ['Iris', 'Rose', 'Jasmine', 'Vetiver'],
      base: ['Opoponax', 'Benzoin', 'Vanilla', 'Civet', 'Tonka Bean', 'Incense'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.0 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: 'A timeless oriental masterpiece inspired by the Gardens of Shalimar in Lahore.',
    tags: ['classic', 'oriental', 'vintage'],
  },
  {
    id: '16',
    slug: 'light-blue-dolce-gabbana',
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    year: 2001,
    gender: 'women',
    concentration: 'EDT',
    price: 75,
    image: IMAGES[15],
    accords: [
      { name: 'Fresh', intensity: 85 },
      { name: 'Citrus', intensity: 80 },
      { name: 'Floral', intensity: 65 },
      { name: 'Marine', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Sicilian Lemon', 'Apple', 'Cedar'],
      heart: ['Bamboo', 'Jasmine', 'White Rose'],
      base: ['Cedarwood', 'Musk', 'Amber'],
    },
    ratings: { longevity: 2, sillage: 2, overall: 7.8 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'beach', 'outdoor'],
    description: 'A carefree Mediterranean summer — fresh, clean and effortlessly beautiful.',
    tags: ['fresh', 'summer', 'popular'],
  },
  {
    id: '17',
    slug: 'angel-thierry-mugler',
    name: 'Angel',
    brand: 'Thierry Mugler',
    year: 1992,
    gender: 'women',
    concentration: 'EDP',
    price: 100,
    image: IMAGES[16],
    accords: [
      { name: 'Sweet', intensity: 92 },
      { name: 'Gourmand', intensity: 85 },
      { name: 'Fruity', intensity: 70 },
      { name: 'Woody', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Red Berries', 'Melon', 'Coconut'],
      heart: ['Honey', 'Orchid', 'Jasmine'],
      base: ['Patchouli', 'Vanilla', 'Cocoa', 'Musk'],
    },
    ratings: { longevity: 5, sillage: 5, overall: 8.7 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'The revolutionary gourmand — a heavenly angel meets the dark earth of patchouli.',
    tags: ['sweet', 'gourmand', 'iconic'],
  },
  {
    id: '18',
    slug: 'portrait-of-a-lady-fm',
    name: 'Portrait of a Lady',
    brand: 'Frédéric Malle',
    year: 2010,
    gender: 'women',
    concentration: 'EDP',
    price: 380,
    image: IMAGES[17],
    accords: [
      { name: 'Floral', intensity: 88 },
      { name: 'Woody', intensity: 70 },
      { name: 'Spicy', intensity: 65 },
      { name: 'Smoky', intensity: 55 },
      { name: 'Sweet', intensity: 45 },
    ],
    notes: {
      top: ['Raspberry'],
      heart: ['Turkish Rose', 'Moroccan Rose', 'Blackcurrant', 'Clove', 'Cinnamon', 'Sandalwood'],
      base: ['Musk', 'Amber', 'Patchouli', 'Frankincense'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.3 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: 'A modern masterpiece — a commanding rose that walks between garden and smoke.',
    tags: ['rose', 'luxury', 'artistic'],
  },
  {
    id: '19',
    slug: 'libre-ysl',
    name: 'Libre',
    brand: 'Yves Saint Laurent',
    year: 2019,
    gender: 'women',
    concentration: 'EDP',
    price: 125,
    image: IMAGES[18],
    accords: [
      { name: 'Floral', intensity: 78 },
      { name: 'Aromatic', intensity: 70 },
      { name: 'Sweet', intensity: 60 },
      { name: 'Warm', intensity: 55 },
      { name: 'Powdery', intensity: 48 },
    ],
    notes: {
      top: ['Mandarin Orange', 'Black Currant'],
      heart: ['Lavender', 'Orange Blossom'],
      base: ['Vanilla', 'Musk', 'Ambergris', 'Cedar'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.7 },
    seasons: ['Fall', 'Spring'],
    occasions: ['everyday', 'date-night', 'evening'],
    description: 'A revolutionary contrast of French lavender and Moroccan orange blossom — bold, free.',
    tags: ['floral', 'feminine', 'modern'],
  },
  {
    id: '20',
    slug: 'terre-d-hermes',
    name: "Terre d'Hermès",
    brand: 'Hermès',
    year: 2006,
    gender: 'men',
    concentration: 'EDP',
    price: 130,
    image: IMAGES[19],
    accords: [
      { name: 'Woody', intensity: 82 },
      { name: 'Earthy', intensity: 75 },
      { name: 'Citrus', intensity: 68 },
      { name: 'Spicy', intensity: 55 },
      { name: 'Mineral', intensity: 50 },
    ],
    notes: {
      top: ['Orange', 'Grapefruit'],
      heart: ['Pepper', 'Pelargonium', 'Vetiver', 'Flint'],
      base: ['Benzoin', 'Cedar', 'Patchouli'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.8 },
    seasons: ['Spring', 'Fall'],
    occasions: ['everyday', 'office', 'outdoor'],
    description: 'A journey from sky to earth — orange zest meets mineral flint and woody depth.',
    tags: ['woody', 'masculine', 'versatile'],
  },
  {
    id: '21',
    slug: 'jo-malone-lime-basil',
    name: 'Lime Basil & Mandarin',
    brand: 'Jo Malone London',
    year: 1999,
    gender: 'unisex',
    concentration: 'Cologne',
    price: 160,
    image: IMAGES[20],
    accords: [
      { name: 'Citrus', intensity: 88 },
      { name: 'Aromatic', intensity: 75 },
      { name: 'Fresh', intensity: 70 },
      { name: 'Green', intensity: 60 },
      { name: 'Woody', intensity: 42 },
    ],
    notes: {
      top: ['Lime', 'Mandarin Orange'],
      heart: ['Basil', 'Lily of the Valley'],
      base: ['Amber', 'White Musk', 'Oakmoss'],
    },
    ratings: { longevity: 2, sillage: 2, overall: 7.9 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'office', 'brunch'],
    description: 'A peppery warmth with exotic Caribbean lime and fresh basil — utterly British.',
    tags: ['citrus', 'unisex', 'everyday'],
  },
  {
    id: '22',
    slug: 'the-one-dolce-gabbana',
    name: 'The One',
    brand: 'Dolce & Gabbana',
    year: 2008,
    gender: 'men',
    concentration: 'EDT',
    price: 90,
    image: IMAGES[21],
    accords: [
      { name: 'Spicy', intensity: 78 },
      { name: 'Woody', intensity: 72 },
      { name: 'Oriental', intensity: 65 },
      { name: 'Sweet', intensity: 58 },
      { name: 'Warm', intensity: 52 },
    ],
    notes: {
      top: ['Grapefruit', 'Coriander', 'Basil', 'Cardamom'],
      heart: ['Ginger', 'Orange Blossom', 'Tobacco'],
      base: ['Cedar', 'Amber', 'Musk', 'Sandalwood'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.5 },
    seasons: ['Fall', 'Winter'],
    occasions: ['date-night', 'evening', 'everyday'],
    description: 'A rich oriental tobacco fragrance with spice and warmth — seductively masculine.',
    tags: ['spicy', 'masculine', 'oriental'],
  },
  {
    id: '23',
    slug: 'narciso-rodriguez-for-her',
    name: 'For Her',
    brand: 'Narciso Rodriguez',
    year: 2003,
    gender: 'women',
    concentration: 'EDP',
    price: 105,
    image: IMAGES[22],
    accords: [
      { name: 'Musky', intensity: 90 },
      { name: 'Floral', intensity: 75 },
      { name: 'Powdery', intensity: 68 },
      { name: 'Warm', intensity: 55 },
      { name: 'Woody', intensity: 45 },
    ],
    notes: {
      top: ['Rose', 'Peach'],
      heart: ['Musk', 'Rose'],
      base: ['Sandalwood', 'Amber', 'Vetiver'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.6 },
    seasons: ['Fall', 'Winter', 'Spring'],
    occasions: ['everyday', 'date-night'],
    description: 'A sensual musk layered with rose — intimate and deeply feminine.',
    tags: ['musky', 'feminine', 'date-night'],
  },
  {
    id: '24',
    slug: 'velvet-rose-oud-zara',
    name: 'Velvet Rose & Oud',
    brand: 'Zara',
    year: 2019,
    gender: 'unisex',
    concentration: 'EDP',
    price: 28,
    image: IMAGES[23],
    accords: [
      { name: 'Rose', intensity: 85 },
      { name: 'Oud', intensity: 75 },
      { name: 'Woody', intensity: 65 },
      { name: 'Spicy', intensity: 50 },
      { name: 'Sweet', intensity: 45 },
    ],
    notes: {
      top: ['Rose', 'Saffron'],
      heart: ['Oud', 'Patchouli'],
      base: ['Sandalwood', 'Musk', 'Amber'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 7.8 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'everyday'],
    description: 'An affordable oud rose dupe that punches well above its price point.',
    dupeOf: 'Portrait of a Lady by Frédéric Malle',
    tags: ['dupe', 'budget', 'oud'],
  },
  {
    id: '25',
    slug: 'born-in-roma-valentino',
    name: 'Born in Roma',
    brand: 'Valentino',
    year: 2019,
    gender: 'women',
    concentration: 'EDP',
    price: 130,
    image: IMAGES[24],
    accords: [
      { name: 'Floral', intensity: 80 },
      { name: 'Woody', intensity: 65 },
      { name: 'Sweet', intensity: 58 },
      { name: 'Musky', intensity: 52 },
      { name: 'Warm', intensity: 45 },
    ],
    notes: {
      top: ['Bergamot', 'White Pepper'],
      heart: ['Tuberose', 'Jasmine'],
      base: ['Sandalwood', 'Musk', 'Vanilla'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.4 },
    seasons: ['Spring', 'Fall'],
    occasions: ['everyday', 'date-night'],
    description: 'A clash of roman street style and high couture — jasmine meets pepper.',
    tags: ['floral', 'feminine', 'modern'],
  },
  {
    id: '26',
    slug: 'invictus-paco-rabanne',
    name: 'Invictus',
    brand: 'Paco Rabanne',
    year: 2013,
    gender: 'men',
    concentration: 'EDT',
    price: 85,
    image: IMAGES[25],
    accords: [
      { name: 'Fresh', intensity: 85 },
      { name: 'Marine', intensity: 75 },
      { name: 'Woody', intensity: 62 },
      { name: 'Citrus', intensity: 58 },
      { name: 'Musky', intensity: 50 },
    ],
    notes: {
      top: ['Grapefruit', 'Sea Notes', 'Green Mandarin'],
      heart: ['Bay Laurel', 'Jasmine', 'Guaiac Wood'],
      base: ['Ambergris', 'Patchouli', 'Oakmoss'],
    },
    ratings: { longevity: 3, sillage: 4, overall: 8.2 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'gym', 'outdoor'],
    description: 'Victory has never smelled so fresh — sport meets sea in this masculine powerhouse.',
    tags: ['fresh', 'sporty', 'masculine'],
  },
  {
    id: '27',
    slug: 'dolce-vita-dior',
    name: 'Dolce Vita',
    brand: 'Dior',
    year: 1994,
    gender: 'women',
    concentration: 'EDT',
    price: 95,
    image: IMAGES[26],
    accords: [
      { name: 'Floral', intensity: 80 },
      { name: 'Fruity', intensity: 68 },
      { name: 'Powdery', intensity: 62 },
      { name: 'Warm', intensity: 55 },
      { name: 'Creamy', intensity: 50 },
    ],
    notes: {
      top: ['Peach', 'Mandarin', 'Camellia'],
      heart: ['Rose', 'Magnolia', 'Lily of the Valley'],
      base: ['Sandalwood', 'Musk', 'Amber', 'Vanilla'],
    },
    ratings: { longevity: 3, sillage: 2, overall: 8.0 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'brunch'],
    description: 'A joyful Mediterranean dream — soft peach and floral harmony.',
    tags: ['floral', 'vintage', 'feminine'],
  },
  {
    id: '28',
    slug: 'boss-bottled-hugo-boss',
    name: 'Boss Bottled',
    brand: 'Hugo Boss',
    year: 1998,
    gender: 'men',
    concentration: 'EDT',
    price: 70,
    image: IMAGES[27],
    accords: [
      { name: 'Fruity', intensity: 75 },
      { name: 'Spicy', intensity: 70 },
      { name: 'Woody', intensity: 65 },
      { name: 'Warm', intensity: 58 },
      { name: 'Aromatic', intensity: 52 },
    ],
    notes: {
      top: ['Apple', 'Plum', 'Bergamot', 'Lemon', 'Geranium'],
      heart: ['Cinnamon', 'Carnation', 'Cloves'],
      base: ['Sandalwood', 'Vanilla', 'Cedar', 'Vetiver', 'Olive Tree'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 7.9 },
    seasons: ['Fall', 'Winter'],
    occasions: ['office', 'everyday'],
    description: 'A powerhouse of the 90s that shaped modern masculinity — apple and warm spice.',
    tags: ['classic', 'office', 'masculine'],
  },
  {
    id: '29',
    slug: 'rose-31-le-labo',
    name: 'Rose 31',
    brand: 'Le Labo',
    year: 2006,
    gender: 'unisex',
    concentration: 'EDP',
    price: 195,
    image: IMAGES[28],
    accords: [
      { name: 'Rose', intensity: 82 },
      { name: 'Woody', intensity: 70 },
      { name: 'Spicy', intensity: 65 },
      { name: 'Musky', intensity: 55 },
      { name: 'Earthy', intensity: 48 },
    ],
    notes: {
      top: ['Rose', 'Cumin'],
      heart: ['Cedar', 'Vetiver', 'Cistus'],
      base: ['Musk', 'Gaiac Wood', 'Incense'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.7 },
    seasons: ['Spring', 'Fall'],
    occasions: ['everyday', 'date-night'],
    description: 'Rose without gender — a woody, slightly animalic modern rose for all.',
    tags: ['rose', 'unisex', 'artisan'],
  },
  {
    id: '30',
    slug: 'hypnotic-poison-dior',
    name: 'Hypnotic Poison',
    brand: 'Dior',
    year: 1998,
    gender: 'women',
    concentration: 'EDT',
    price: 100,
    image: IMAGES[29],
    accords: [
      { name: 'Sweet', intensity: 85 },
      { name: 'Powdery', intensity: 78 },
      { name: 'Warm', intensity: 70 },
      { name: 'Almond', intensity: 68 },
      { name: 'Vanilla', intensity: 60 },
    ],
    notes: {
      top: ['Apricot', 'Plum', 'Coconut'],
      heart: ['Jasmine', 'Rosewood', 'Tuberose'],
      base: ['Almond', 'Musk', 'Sandalwood', 'Vanilla', 'Caraway'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.6 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'Dangerously addictive — almond, tuberose and vanilla in a hypnotic embrace.',
    tags: ['sweet', 'feminine', 'evening'],
  },
  {
    id: '31',
    slug: 'santal-33-le-labo',
    name: 'Santal 33',
    brand: 'Le Labo',
    year: 2011,
    gender: 'unisex',
    concentration: 'EDP',
    price: 215,
    image: IMAGES[30],
    accords: [
      { name: 'Woody', intensity: 88 },
      { name: 'Earthy', intensity: 72 },
      { name: 'Smoky', intensity: 65 },
      { name: 'Musky', intensity: 58 },
      { name: 'Spicy', intensity: 50 },
    ],
    notes: {
      top: ['Cardamom', 'Iris', 'Violet'],
      heart: ['Ambrette', 'Sandalwood', 'Australian Sandalwood', 'Cedarwood'],
      base: ['Leather', 'Musk', 'Amber'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.9 },
    seasons: ['Fall', 'Winter', 'Spring'],
    occasions: ['everyday', 'office'],
    description: 'The fragrance that broke the internet — iconic sandalwood for the creative class.',
    tags: ['woody', 'unisex', 'iconic'],
  },
  {
    id: '32',
    slug: 'coco-mademoiselle-chanel',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    year: 2001,
    gender: 'women',
    concentration: 'EDP',
    price: 155,
    image: IMAGES[31],
    accords: [
      { name: 'Oriental', intensity: 82 },
      { name: 'Floral', intensity: 75 },
      { name: 'Citrus', intensity: 68 },
      { name: 'Woody', intensity: 62 },
      { name: 'Musky', intensity: 55 },
    ],
    notes: {
      top: ['Orange', 'Bergamot', 'Grapefruit'],
      heart: ['Mimosa', 'Rose', 'Jasmine'],
      base: ['Patchouli', 'Vetiver', 'White Musk', 'Oud', 'Tonka Bean'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.8 },
    seasons: ['Spring', 'Fall'],
    occasions: ['everyday', 'office', 'date-night'],
    description: 'A playful, ultra-fresh oriental from Chanel — always sophisticated, always daring.',
    tags: ['classic', 'feminine', 'versatile'],
  },
  {
    id: '33',
    slug: 'wanted-azzaro',
    name: 'Wanted',
    brand: 'Azzaro',
    year: 2016,
    gender: 'men',
    concentration: 'EDT',
    price: 65,
    image: IMAGES[32],
    accords: [
      { name: 'Spicy', intensity: 80 },
      { name: 'Woody', intensity: 72 },
      { name: 'Citrus', intensity: 65 },
      { name: 'Aromatic', intensity: 58 },
      { name: 'Warm', intensity: 52 },
    ],
    notes: {
      top: ['Grapefruit', 'Cardamom', 'Lemon'],
      heart: ['Juniperberry', 'Cabreuva Wood'],
      base: ['Suede', 'Guaiac Wood'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 8.0 },
    seasons: ['Spring', 'Fall'],
    occasions: ['everyday', 'date-night'],
    description: 'A confident, daring take on modern masculinity with spice and citrus.',
    tags: ['spicy', 'masculine', 'value'],
  },
  {
    id: '34',
    slug: 'chanel-no5',
    name: 'Chanel No. 5',
    brand: 'Chanel',
    year: 1921,
    gender: 'women',
    concentration: 'EDP',
    price: 145,
    image: IMAGES[33],
    accords: [
      { name: 'Powdery', intensity: 88 },
      { name: 'Floral', intensity: 82 },
      { name: 'Aldehyde', intensity: 75 },
      { name: 'Vanilla', intensity: 55 },
      { name: 'Musky', intensity: 50 },
    ],
    notes: {
      top: ['Aldehydes', 'Bergamot', 'Neroli', 'Ylang-Ylang'],
      heart: ['Iris', 'Jasmine', 'Lily of the Valley', 'Rose'],
      base: ['Civet', 'Oakmoss', 'Sandalwood', 'Vetiver'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.2 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: "The fragrance that changed everything — the world's most famous perfume.",
    tags: ['iconic', 'classic', 'legendary'],
  },
  {
    id: '35',
    slug: 'la-nuit-tresor-lancome',
    name: 'La Nuit Trésor',
    brand: 'Lancôme',
    year: 2015,
    gender: 'women',
    concentration: 'EDP',
    price: 105,
    image: IMAGES[34],
    accords: [
      { name: 'Sweet', intensity: 85 },
      { name: 'Floral', intensity: 72 },
      { name: 'Fruity', intensity: 65 },
      { name: 'Vanilla', intensity: 60 },
      { name: 'Musky', intensity: 48 },
    ],
    notes: {
      top: ['Black Currant'],
      heart: ['Rose', 'Damask Rose'],
      base: ['Vanilla', 'Praline', 'Patchouli'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.5 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'A sensual and mysterious rose for the night — blackcurrant and praline.',
    tags: ['sweet', 'feminine', 'evening'],
  },
  {
    id: '36',
    slug: 'polo-red-ralph-lauren',
    name: 'Polo Red',
    brand: 'Ralph Lauren',
    year: 2013,
    gender: 'men',
    concentration: 'EDT',
    price: 75,
    image: IMAGES[35],
    accords: [
      { name: 'Fruity', intensity: 82 },
      { name: 'Fresh', intensity: 72 },
      { name: 'Woody', intensity: 65 },
      { name: 'Citrus', intensity: 60 },
      { name: 'Aromatic', intensity: 50 },
    ],
    notes: {
      top: ['Grapefruit', 'Cranberry', 'Saffron', 'Lemon'],
      heart: ['Coffee', 'Rose', 'Sage'],
      base: ['Guaiac Wood', 'Birchwood'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 7.9 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'outdoor', 'gym'],
    description: 'Intensity, sensuality, passion — red grapefruit and guaiac wood in motion.',
    tags: ['fruity', 'masculine', 'sporty'],
  },
  {
    id: '37',
    slug: 'euphoria-calvin-klein',
    name: 'Euphoria',
    brand: 'Calvin Klein',
    year: 2005,
    gender: 'women',
    concentration: 'EDP',
    price: 75,
    image: IMAGES[36],
    accords: [
      { name: 'Floral', intensity: 78 },
      { name: 'Sweet', intensity: 70 },
      { name: 'Fruity', intensity: 65 },
      { name: 'Woody', intensity: 55 },
      { name: 'Musky', intensity: 50 },
    ],
    notes: {
      top: ['Pomegranate', 'Persimmon', 'Green Notes'],
      heart: ['Black Orchid', 'Black Violet', 'Lotus'],
      base: ['Black Amber', 'Mahogany', 'Cream'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.2 },
    seasons: ['Fall', 'Winter'],
    occasions: ['date-night', 'evening'],
    description: 'A seductive and mysterious floral — pomegranate meets black orchid.',
    tags: ['floral', 'feminine', 'dark'],
  },
  {
    id: '38',
    slug: 'replica-jazz-club',
    name: 'Jazz Club',
    brand: 'Maison Margiela Replica',
    year: 2013,
    gender: 'unisex',
    concentration: 'EDT',
    price: 160,
    image: IMAGES[37],
    accords: [
      { name: 'Tobacco', intensity: 85 },
      { name: 'Warm', intensity: 78 },
      { name: 'Sweet', intensity: 68 },
      { name: 'Spicy', intensity: 58 },
      { name: 'Woody', intensity: 50 },
    ],
    notes: {
      top: ['Pink Pepper', 'Neroli', 'Lemon'],
      heart: ['Rum', 'Clary Sage', 'Musk'],
      base: ['Tobacco', 'Vanilla', 'Vetiver'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.8 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night', 'special-occasion'],
    description: 'Smoky rum, warm tobacco and sweet vanilla — a late-night jazz club captured.',
    tags: ['tobacco', 'unisex', 'evening'],
  },
  {
    id: '39',
    slug: 'scandal-jean-paul-gaultier',
    name: 'Scandal',
    brand: 'Jean Paul Gaultier',
    year: 2017,
    gender: 'women',
    concentration: 'EDP',
    price: 95,
    image: IMAGES[38],
    accords: [
      { name: 'Sweet', intensity: 82 },
      { name: 'Floral', intensity: 75 },
      { name: 'Honey', intensity: 70 },
      { name: 'Warm', intensity: 60 },
      { name: 'Fruity', intensity: 50 },
    ],
    notes: {
      top: ['Blood Orange', 'Tangerine'],
      heart: ['Gardenia', 'Honey'],
      base: ['Patchouli', 'Vetiver'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.4 },
    seasons: ['Fall', 'Winter', 'Spring'],
    occasions: ['evening', 'date-night', 'everyday'],
    description: 'Honey meets gardenia in a scandalously sweet and provocative femme fragrance.',
    tags: ['sweet', 'feminine', 'floral'],
  },
  {
    id: '40',
    slug: 'myrrhe-encens-hermes',
    name: 'Myrrhe & Encens',
    brand: 'Hermès',
    year: 2021,
    gender: 'unisex',
    concentration: 'Parfum',
    price: 310,
    image: IMAGES[39],
    accords: [
      { name: 'Incense', intensity: 90 },
      { name: 'Smoky', intensity: 78 },
      { name: 'Spicy', intensity: 65 },
      { name: 'Woody', intensity: 60 },
      { name: 'Warm', intensity: 55 },
    ],
    notes: {
      top: ['Myrrh', 'Elemi'],
      heart: ['Frankincense', 'Cistus'],
      base: ['Olibanum', 'Benzoin', 'Sandalwood'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.0 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: 'A meditative rite of smoke — sacred resins, incense and amber from Hermès.',
    tags: ['incense', 'luxury', 'unisex'],
  },
  {
    id: '41',
    slug: 'dior-homme-intense',
    name: 'Dior Homme Intense',
    brand: 'Dior',
    year: 2007,
    gender: 'men',
    concentration: 'EDP',
    price: 130,
    image: IMAGES[40],
    accords: [
      { name: 'Powdery', intensity: 85 },
      { name: 'Floral', intensity: 72 },
      { name: 'Woody', intensity: 65 },
      { name: 'Sweet', intensity: 58 },
      { name: 'Warm', intensity: 52 },
    ],
    notes: {
      top: ['Bergamot', 'Lavender'],
      heart: ['Iris', 'Pear', 'Ambrette'],
      base: ['Vetiver', 'Patchouli', 'Virginia Cedar'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 9.0 },
    seasons: ['Fall', 'Winter'],
    occasions: ['date-night', 'evening'],
    description: 'A powdery iris masterpiece redefining masculinity — refined and deeply seductive.',
    tags: ['iris', 'masculine', 'powdery'],
  },
  {
    id: '42',
    slug: 'versace-eros',
    name: 'Eros',
    brand: 'Versace',
    year: 2012,
    gender: 'men',
    concentration: 'EDT',
    price: 80,
    image: IMAGES[41],
    accords: [
      { name: 'Fresh', intensity: 82 },
      { name: 'Woody', intensity: 70 },
      { name: 'Sweet', intensity: 65 },
      { name: 'Aromatic', intensity: 60 },
      { name: 'Citrus', intensity: 55 },
    ],
    notes: {
      top: ['Mint', 'Green Apple', 'Lemon'],
      heart: ['Ambroxan', 'Tonka Bean', 'Geranium'],
      base: ['Cedarwood', 'Atlas Cedar', 'Vetiver', 'Oakmoss'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.3 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'gym', 'date-night'],
    description: 'The god of love in a bottle — minty fresh top over warm woody vanilla.',
    tags: ['fresh', 'masculine', 'popular'],
  },
  {
    id: '43',
    slug: 'mon-paris-ysl',
    name: 'Mon Paris',
    brand: 'Yves Saint Laurent',
    year: 2016,
    gender: 'women',
    concentration: 'EDP',
    price: 110,
    image: IMAGES[42],
    accords: [
      { name: 'Floral', intensity: 82 },
      { name: 'Fruity', intensity: 75 },
      { name: 'Sweet', intensity: 68 },
      { name: 'Musky', intensity: 55 },
      { name: 'Woody', intensity: 48 },
    ],
    notes: {
      top: ['Strawberry', 'Raspberry', 'Pear'],
      heart: ['Peony', 'Rose', 'White Flowers'],
      base: ['Musk', 'Patchouli', 'White Amber'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.5 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'date-night'],
    description: 'A love story à la Parisienne — fresh fruits tumbling into white florals.',
    tags: ['floral', 'feminine', 'fruity'],
  },
  {
    id: '44',
    slug: 'polo-blue-ralph-lauren',
    name: 'Polo Blue',
    brand: 'Ralph Lauren',
    year: 2003,
    gender: 'men',
    concentration: 'EDT',
    price: 70,
    image: IMAGES[43],
    accords: [
      { name: 'Aquatic', intensity: 85 },
      { name: 'Fresh', intensity: 80 },
      { name: 'Woody', intensity: 65 },
      { name: 'Citrus', intensity: 60 },
      { name: 'Musky', intensity: 48 },
    ],
    notes: {
      top: ['Cucumber', 'Melon', 'Sage'],
      heart: ['Basil', 'Geranium', 'White Pepper'],
      base: ['Suede', 'Musk', 'Vetiver'],
    },
    ratings: { longevity: 3, sillage: 3, overall: 7.8 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'outdoor'],
    description: 'A crisp aquatic gentleman — cucumber, sage and suede on a summer breeze.',
    tags: ['aquatic', 'masculine', 'summer'],
  },
  {
    id: '45',
    slug: 'black-opium-ysl',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    year: 2014,
    gender: 'women',
    concentration: 'EDP',
    price: 115,
    image: IMAGES[44],
    accords: [
      { name: 'Sweet', intensity: 88 },
      { name: 'Gourmand', intensity: 80 },
      { name: 'Floral', intensity: 65 },
      { name: 'Coffee', intensity: 62 },
      { name: 'Warm', intensity: 55 },
    ],
    notes: {
      top: ['Pink Pepper', 'Orange Blossom', 'Pear'],
      heart: ['Coffee', 'Jasmine', 'Bitter Almond'],
      base: ['Patchouli', 'Vanilla', 'Cedarwood', 'Cashmeran'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.7 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'Addictively edgy — dark coffee and white florals wrapped in sweet vanilla.',
    tags: ['coffee', 'sweet', 'feminine'],
  },
  {
    id: '46',
    slug: 'aoud-by-roja-dove',
    name: 'Aoud',
    brand: 'Roja Dove',
    year: 2008,
    gender: 'unisex',
    concentration: 'Parfum',
    price: 560,
    image: IMAGES[45],
    accords: [
      { name: 'Oud', intensity: 95 },
      { name: 'Rose', intensity: 80 },
      { name: 'Spicy', intensity: 70 },
      { name: 'Woody', intensity: 65 },
      { name: 'Floral', intensity: 55 },
    ],
    notes: {
      top: ['Rose', 'Coriander', 'Pink Pepper'],
      heart: ['Oud', 'Jasmine', 'Incense'],
      base: ['Sandalwood', 'Ambergris', 'Musk', 'Vanilla'],
    },
    ratings: { longevity: 5, sillage: 5, overall: 9.4 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'special-occasion'],
    description: 'The pinnacle of oud perfumery — breathtakingly opulent and utterly unique.',
    tags: ['oud', 'ultra-luxury', 'unisex'],
  },
  {
    id: '47',
    slug: 'mon-guerlain',
    name: 'Mon Guerlain',
    brand: 'Guerlain',
    year: 2017,
    gender: 'women',
    concentration: 'EDP',
    price: 115,
    image: IMAGES[46],
    accords: [
      { name: 'Sweet', intensity: 80 },
      { name: 'Floral', intensity: 75 },
      { name: 'Vanilla', intensity: 70 },
      { name: 'Warm', intensity: 60 },
      { name: 'Powdery', intensity: 50 },
    ],
    notes: {
      top: ['Bergamot'],
      heart: ['Lavender', 'Jasmine Sambac'],
      base: ['Vanilla', 'Sandalwood', 'Vetiver'],
    },
    ratings: { longevity: 4, sillage: 3, overall: 8.4 },
    seasons: ['Spring', 'Summer', 'Fall'],
    occasions: ['everyday', 'brunch'],
    description: 'My Guerlain — lavender meets sandalwood and vanilla in feminine harmony.',
    tags: ['sweet', 'feminine', 'versatile'],
  },
  {
    id: '48',
    slug: 'paco-rabanne-1-million',
    name: '1 Million',
    brand: 'Paco Rabanne',
    year: 2008,
    gender: 'men',
    concentration: 'EDT',
    price: 88,
    image: IMAGES[47],
    accords: [
      { name: 'Sweet', intensity: 82 },
      { name: 'Spicy', intensity: 75 },
      { name: 'Fruity', intensity: 68 },
      { name: 'Warm', intensity: 62 },
      { name: 'Leather', intensity: 55 },
    ],
    notes: {
      top: ['Grapefruit', 'Mint', 'Blood Mandarin'],
      heart: ['Cinnamon', 'Rose', 'Spice'],
      base: ['Leather', 'Wood', 'Amber', 'Patchouli'],
    },
    ratings: { longevity: 4, sillage: 4, overall: 8.4 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'Bold, brash and beloved — spiced leather and grapefruit for the confident man.',
    tags: ['spicy', 'masculine', 'date-night'],
  },
  {
    id: '49',
    slug: 'l-eau-issey-miyake',
    name: "L'Eau d'Issey",
    brand: 'Issey Miyake',
    year: 1992,
    gender: 'women',
    concentration: 'EDT',
    price: 70,
    image: IMAGES[48],
    accords: [
      { name: 'Aquatic', intensity: 88 },
      { name: 'Fresh', intensity: 82 },
      { name: 'Floral', intensity: 65 },
      { name: 'Powdery', intensity: 55 },
      { name: 'Musky', intensity: 45 },
    ],
    notes: {
      top: ['Lotus', 'Cyclamen', 'Rose', 'Peony'],
      heart: ['Calone', 'Lily', 'Carnation'],
      base: ['Musk', 'Cedar', 'Sandalwood', 'Amber'],
    },
    ratings: { longevity: 3, sillage: 2, overall: 7.9 },
    seasons: ['Spring', 'Summer'],
    occasions: ['everyday', 'office', 'brunch'],
    description: 'Water as perfume — the original aquatic floral that launched a revolution.',
    tags: ['aquatic', 'feminine', 'classic'],
  },
  {
    id: '50',
    slug: 'patchouli-24-le-labo',
    name: 'Patchouli 24',
    brand: 'Le Labo',
    year: 2006,
    gender: 'unisex',
    concentration: 'EDP',
    price: 195,
    image: IMAGES[49],
    accords: [
      { name: 'Woody', intensity: 85 },
      { name: 'Smoky', intensity: 80 },
      { name: 'Earthy', intensity: 72 },
      { name: 'Vanilla', intensity: 60 },
      { name: 'Musky', intensity: 55 },
    ],
    notes: {
      top: ['Juniper'],
      heart: ['Birch Tar', 'Cade'],
      base: ['Patchouli', 'Vanilla', 'Musk'],
    },
    ratings: { longevity: 5, sillage: 4, overall: 8.8 },
    seasons: ['Fall', 'Winter'],
    occasions: ['evening', 'date-night'],
    description: 'Campfire and tar and vanilla — a bold, polarising cult classic.',
    tags: ['smoky', 'unisex', 'niche'],
  },
];

export function getPerfumeBySlug(slug: string): Perfume | undefined {
  return PERFUMES.find((p) => p.slug === slug);
}

export function getPerfumesByBrand(brand: string): Perfume[] {
  return PERFUMES.filter((p) => p.brand === brand);
}

export function getPerfumesByGender(gender: string): Perfume[] {
  return PERFUMES.filter((p) => p.gender === gender);
}

export function getPerfumesByNote(note: string): Perfume[] {
  return PERFUMES.filter((p) =>
    [...p.notes.top, ...p.notes.heart, ...p.notes.base]
      .some((n) => n.toLowerCase().includes(note.toLowerCase()))
  );
}

export function getAllBrands(): string[] {
  const seen = new Set<string>();
  return PERFUMES.map((p) => p.brand).filter((b) => {
    if (seen.has(b)) return false;
    seen.add(b);
    return true;
  }).sort();
}

export function getAllNotes(): string[] {
  const seen = new Set<string>();
  const all: string[] = [];
  PERFUMES.forEach((p) => {
    [...p.notes.top, ...p.notes.heart, ...p.notes.base].forEach((n) => {
      if (!seen.has(n)) { seen.add(n); all.push(n); }
    });
  });
  return all.sort();
}

export function getSimilarPerfumes(perfume: Perfume, count = 4): Perfume[] {
  return PERFUMES
    .filter((p) => p.slug !== perfume.slug)
    .filter((p) => p.gender === perfume.gender || p.gender === 'unisex' || perfume.gender === 'unisex')
    .slice(0, count);
}
